import Characters from 'lanna-utils/dist/resources/characters';
import type { KeyMapping } from '../mapping';

export default [
  { taitham: Characters.letterHighKa, key: 'ก' },
  { taitham: Characters.letterHighKha, key: 'ข' },
  { taitham: Characters.letterHighKxa, key: 'ฃ' },
  { taitham: Characters.letterLowKa, key: 'ค' },
  { taitham: Characters.letterLowKxa, key: 'ฅ' },
  { taitham: Characters.letterLowKha, key: 'ฆ' },
  { taitham: Characters.letterNga, key: 'ง' },
  { taitham: Characters.letterHighCa, key: 'จ' },
  { taitham: Characters.letterHighCha, key: 'ฉ' },
  { taitham: Characters.letterLowCa, key: 'ช' },
  { taitham: Characters.letterLowSa, key: 'ซ' },
  { taitham: Characters.letterLowCha, key: 'ฌ' },
  { taitham: Characters.letterNya, key: 'ญ' },
  { taitham: Characters.letterRata, key: 'ฏ' },
  { taitham: Characters.letterHighRatha, key: 'ฐ' },
  { taitham: Characters.letterDa, key: 'ด' },
  { taitham: Characters.letterLowRatha, key: 'ฒ' },
  { taitham: Characters.letterRana, key: 'ณ' },
  { taitham: Characters.letterHighTa, key: 'ต' },
  { taitham: Characters.letterHighTha, key: 'ถ' },
  { taitham: Characters.letterLowTa, key: 'ท' },
  { taitham: Characters.letterLowTha, key: 'ธ' },
  { taitham: Characters.letterNa, key: 'น' },
  { taitham: Characters.letterBa, key: 'บ' },
  { taitham: Characters.letterHighPa, key: 'ป' },
  { taitham: Characters.letterHighPha, key: 'ผ' },
  { taitham: Characters.letterHighFa, key: 'ฝ' },
  { taitham: Characters.letterLowPa, key: 'พ' },
  { taitham: Characters.letterLowFa, key: 'ฟ' },
  { taitham: Characters.letterLowPha, key: 'ภ' },
  { taitham: Characters.letterMa, key: 'ม' },
  { taitham: Characters.letterLowYa, key: 'ย' },
  { taitham: Characters.letterHighYa, key: '"' },
  { taitham: Characters.letterHighYa, key: 'ย', rShiftCount: 1 },
  { taitham: Characters.letterRa, key: 'ร' },
  { taitham: Characters.letterRue, key: 'ฤ' },
  { taitham: Characters.letterLa, key: 'ล' },
  { taitham: Characters.letterLue, key: 'ฦ' },
  { taitham: Characters.letterWa, key: 'ว' },
  { taitham: Characters.letterHighSha, key: 'ศ' },
  { taitham: Characters.letterHighSsa, key: 'ษ' },
  { taitham: Characters.letterHighSa, key: 'ส' },
  { taitham: Characters.letterHighHa, key: 'ห' },
  { taitham: Characters.letterLla, key: 'ฬ' },
  { taitham: Characters.letterA, key: 'อ' },
  { taitham: Characters.letterLowHa, key: 'ฮ' },
  { taitham: Characters.letterI, key: 'ิ', rShiftCount: 1 },
  { taitham: Characters.letterIi, key: 'ี', rShiftCount: 1 },
  { taitham: Characters.letterU, key: 'ุ', rShiftCount: 1 },
  { taitham: Characters.letterUu, key: 'ู', rShiftCount: 1 },
  { taitham: Characters.letterEe, key: 'เ', rShiftCount: 1 },
  { taitham: Characters.letterOo, key: 'โ', rShiftCount: 1 },
  { taitham: Characters.letterLae, key: ',' },
  { taitham: Characters.letterLae, key: 'ล', rShiftCount: 1 },
  { taitham: Characters.letterGreatSa, key: '.' },
  { taitham: Characters.letterGreatSa, key: 'ส', rShiftCount: 1 },
  { taitham: Characters.consonantSignMedialRa, key: '๊' },
  { taitham: Characters.consonantSignMedialRa, key: 'ร', rShiftCount: 1 },
  { taitham: Characters.consonantSignMedialLa, key: '๋' },
  { taitham: Characters.consonantSignMedialLa, key: 'ล', rShiftCount: 2 },
  { taitham: Characters.consonantSignLaTangLai, key: 'ล', rShiftCount: 3 },
  { taitham: Characters.signMaiKangLai, key: '็' },
  { taitham: Characters.signMaiKangLai, key: 'ง', rShiftCount: 1 },
  { taitham: Characters.consonantSignFinalNga, key: 'ง', rShiftCount: 2 },
  { taitham: Characters.consonantSignLowPa, key: 'พ', rShiftCount: 2 },
  { taitham: Characters.consonantSignHighRathaOrLowPa, key: '(' },
  { taitham: Characters.consonantSignHighRathaOrLowPa, key: 'ฐ', rShiftCount: 1 },
  { taitham: Characters.consonantSignHighRathaOrLowPa, key: 'พ', rShiftCount: 1 },
  { taitham: Characters.consonantSignMa, key: 'ม', rShiftCount: 1 },
  { taitham: Characters.consonantSignBa, key: ')' },
  { taitham: Characters.consonantSignBa, key: 'บ', rShiftCount: 1 },
  { taitham: Characters.consonantSignSa, key: 'ส', rShiftCount: 2 },
  { taitham: Characters.signSakot, key: '_' },
  { taitham: Characters.vowelSignA, key: 'ะ' },
  { taitham: Characters.vowelSignMaiSat, key: 'ั' },
  { taitham: Characters.vowelSignAa, key: 'า' },
  { taitham: Characters.vowelSignTallAa, key: 'ๅ' },
  { taitham: Characters.vowelSignI, key: 'ิ' },
  { taitham: Characters.vowelSignIi, key: 'ี' },
  { taitham: Characters.vowelSignUe, key: 'ึ' },
  { taitham: Characters.vowelSignUue, key: 'ื' },
  { taitham: Characters.vowelSignU, key: 'ุ' },
  { taitham: Characters.vowelSignUu, key: 'ู' },
  { taitham: Characters.vowelSignO, key: 'ฎ' },
  { taitham: Characters.vowelSignO, key: 'ั', rShiftCount: 1 },
  { taitham: Characters.vowelSignOaBelow, key: 'ำ' },
  { taitham: Characters.vowelSignOy, key: 'ย', rShiftCount: 2 },
  { taitham: Characters.vowelSignE, key: 'เ' },
  { taitham: Characters.vowelSignAe, key: 'แ' },
  { taitham: Characters.vowelSignOo, key: 'โ' },
  { taitham: Characters.vowelSignAi, key: 'ไ' },
  { taitham: Characters.vowelSignThamAi, key: 'ใ' },
  { taitham: Characters.vowelSignOaAbove, key: 'อ', rShiftCount: 3 },
  { taitham: Characters.signMaiKang, key: 'ํ' },
  { taitham: Characters.signTone1, key: '่' },
  { taitham: Characters.signTone2, key: '้' },
  { taitham: Characters.signKhuenTone3, key: '่', rShiftCount: 1 },
  { taitham: Characters.signKhuenTone4, key: '้', rShiftCount: 1 },
  { taitham: Characters.signKhuenTone5, key: '๊', rShiftCount: 1 },
  { taitham: Characters.signRaHaam, key: '์' },
  { taitham: Characters.signMaiSam, key: 'ๆ' },
  { taitham: Characters.signKhuenLueKaran, key: '์', rShiftCount: 1 },
  { taitham: Characters.combiningCryptogrammicDot, key: 'ฺ', rShiftCount: 1 },
  { taitham: Characters.horaDigitZero, key: '๐' },
  { taitham: Characters.horaDigitOne, key: '๑' },
  { taitham: Characters.horaDigitTwo, key: '๒' },
  { taitham: Characters.horaDigitThree, key: '๓' },
  { taitham: Characters.horaDigitFour, key: '๔' },
  { taitham: Characters.horaDigitFive, key: '๕' },
  { taitham: Characters.horaDigitSix, key: '๖' },
  { taitham: Characters.horaDigitSeven, key: '๗' },
  { taitham: Characters.horaDigitEight, key: '๘' },
  { taitham: Characters.horaDigitNine, key: '๙' },
  { taitham: Characters.thamDigitZero, key: '๐', rShiftCount: 1 },
  { taitham: Characters.thamDigitOne, key: '๑', rShiftCount: 1 },
  { taitham: Characters.thamDigitTwo, key: '๒', rShiftCount: 1 },
  { taitham: Characters.thamDigitThree, key: '๓', rShiftCount: 1 },
  { taitham: Characters.thamDigitFour, key: '๔', rShiftCount: 1 },
  { taitham: Characters.thamDigitFive, key: '๕', rShiftCount: 1 },
  { taitham: Characters.thamDigitSix, key: '๖', rShiftCount: 1 },
  { taitham: Characters.thamDigitSeven, key: '๗', rShiftCount: 1 },
  { taitham: Characters.thamDigitEight, key: '๘', rShiftCount: 1 },
  { taitham: Characters.thamDigitNine, key: '๙', rShiftCount: 1 },
  { taitham: Characters.signWiang, key: 'ว', rShiftCount: 1 },
  { taitham: Characters.signWiangwaak, key: 'ว', rShiftCount: 2 },
  { taitham: Characters.signSawan, key: 'ส', rShiftCount: 3 },
  { taitham: Characters.signKeow, key: 'ค', rShiftCount: 1 },
  { taitham: Characters.signHoy, key: 'ห', rShiftCount: 1 },
  { taitham: Characters.signDokmai, key: 'ด', rShiftCount: 1 },
  { taitham: Characters.signReversedRotatedRana, key: 'ณ', rShiftCount: 1 },
  { taitham: Characters.signMaiYamok, key: 'ๆ', rShiftCount: 1 },
  { taitham: Characters.signKaan, key: 'ไ', rShiftCount: 1 },
  { taitham: Characters.signKaankuu, key: 'ไ', rShiftCount: 2 },
  { taitham: Characters.signSatkaan, key: 'ฯ' },
  { taitham: Characters.signSatkaankuu, key: 'ฯ', rShiftCount: 1 },
  { taitham: Characters.signHang, key: 'ห', rShiftCount: 2 },
  { taitham: Characters.signCaang, key: 'ช', rShiftCount: 1 }
] as KeyMapping[];
