import Characters from 'lanna-utils/dist/resources/characters';

export type Key = {
  character: string,
  key: string,
  rShiftCount: number
};

export const keys: Key[] = [
  {character: Characters.letterHighKa, key: 'ก', rShiftCount: 0},
  {character: Characters.letterHighKha, key: 'ข', rShiftCount: 0},
  {character: Characters.letterHighKxa, key: 'ฃ', rShiftCount: 0},
  {character: Characters.letterLowKa, key: 'ค', rShiftCount: 0},
  {character: Characters.letterLowKxa, key: 'ฅ', rShiftCount: 0},
  {character: Characters.letterLowKha, key: 'ฆ', rShiftCount: 0},
  {character: Characters.letterNga, key: 'ง', rShiftCount: 0},
  {character: Characters.letterHighCa, key: 'จ', rShiftCount: 0},
  {character: Characters.letterHighCha, key: 'ฉ', rShiftCount: 0},
  {character: Characters.letterLowCa, key: 'ช', rShiftCount: 0},
  {character: Characters.letterLowSa, key: 'ซ', rShiftCount: 0},
  {character: Characters.letterLowCha, key: 'ฌ', rShiftCount: 0},
  {character: Characters.letterNya, key: 'ญ', rShiftCount: 0},
  {character: Characters.letterRata, key: 'ฏ', rShiftCount: 0},
  {character: Characters.letterHighRatha, key: 'ฐ', rShiftCount: 0},
  {character: Characters.letterDa, key: 'ด', rShiftCount: 0},
  {character: Characters.letterLowRatha, key: 'ฒ', rShiftCount: 0},
  {character: Characters.letterRana, key: 'ณ', rShiftCount: 0},
  {character: Characters.letterHighTa, key: 'ต', rShiftCount: 0},
  {character: Characters.letterHighTha, key: 'ถ', rShiftCount: 0},
  {character: Characters.letterLowTa, key: 'ท', rShiftCount: 0},
  {character: Characters.letterLowTha, key: 'ธ', rShiftCount: 0},
  {character: Characters.letterNa, key: 'น', rShiftCount: 0},
  {character: Characters.letterBa, key: 'บ', rShiftCount: 0},
  {character: Characters.letterHighPa, key: 'ป', rShiftCount: 0},
  {character: Characters.letterHighPha, key: 'ผ', rShiftCount: 0},
  {character: Characters.letterHighFa, key: 'ฝ', rShiftCount: 0},
  {character: Characters.letterLowPa, key: 'พ', rShiftCount: 0},
  {character: Characters.letterLowFa, key: 'ฟ', rShiftCount: 0},
  {character: Characters.letterLowPha, key: 'ภ', rShiftCount: 0},
  {character: Characters.letterMa, key: 'ม', rShiftCount: 0},
  {character: Characters.letterLowYa, key: 'ย', rShiftCount: 0},
  {character: Characters.letterHighYa, key: '"', rShiftCount: 0},
  {character: Characters.letterHighYa, key: 'ย', rShiftCount: 1},
  {character: Characters.letterRa, key: 'ร', rShiftCount: 0},
  {character: Characters.letterRue, key: 'ฤ', rShiftCount: 0},
  {character: Characters.letterLa, key: 'ล', rShiftCount: 0},
  {character: Characters.letterLue, key: 'ฦ', rShiftCount: 0},
  {character: Characters.letterWa, key: 'ว', rShiftCount: 0},
  {character: Characters.letterHighSha, key: 'ศ', rShiftCount: 0},
  {character: Characters.letterHighSsa, key: 'ษ', rShiftCount: 0},
  {character: Characters.letterHighSa, key: 'ส', rShiftCount: 0},
  {character: Characters.letterHighHa, key: 'ห', rShiftCount: 0},
  {character: Characters.letterLla, key: 'ฬ', rShiftCount: 0},
  {character: Characters.letterA, key: 'อ', rShiftCount: 0},
  {character: Characters.letterLowHa, key: 'ฮ', rShiftCount: 0},
  {character: Characters.letterI, key: 'ิ', rShiftCount: 1},
  {character: Characters.letterIi, key: 'ี', rShiftCount: 1},
  {character: Characters.letterU, key: 'ุ', rShiftCount: 1},
  {character: Characters.letterUu, key: 'ู', rShiftCount: 1},
  {character: Characters.letterEe, key: 'เ', rShiftCount: 1},
  {character: Characters.letterOo, key: 'โ', rShiftCount: 1},
  {character: Characters.letterLae, key: ',', rShiftCount: 0},
  {character: Characters.letterLae, key: 'ล', rShiftCount: 1},
  {character: Characters.letterGreatSa, key: '.', rShiftCount: 0},
  {character: Characters.letterGreatSa, key: 'ส', rShiftCount: 1},
  {character: Characters.consonantSignMedialRa, key: '๊', rShiftCount: 0},
  {character: Characters.consonantSignMedialRa, key: 'ร', rShiftCount: 1},
  {character: Characters.consonantSignMedialLa, key: '๋', rShiftCount: 0},
  {character: Characters.consonantSignMedialLa, key: 'ล', rShiftCount: 2},
  {character: Characters.consonantSignLaTangLai, key: 'ล', rShiftCount: 3},
  {character: Characters.signMaiKangLai, key: '็', rShiftCount: 0},
  {character: Characters.signMaiKangLai, key: 'ง', rShiftCount: 1},
  {character: Characters.consonantSignFinalNga, key: 'ง', rShiftCount: 2},
  {character: Characters.consonantSignLowPa, key: 'พ', rShiftCount: 2},
  {character: Characters.consonantSignHighRathaOrLowPa, key: '(', rShiftCount: 0},
  {character: Characters.consonantSignHighRathaOrLowPa, key: 'ฐ', rShiftCount: 1},
  {character: Characters.consonantSignHighRathaOrLowPa, key: 'พ', rShiftCount: 1},
  {character: Characters.consonantSignMa, key: 'ม', rShiftCount: 1},
  {character: Characters.consonantSignBa, key: ')', rShiftCount: 0},
  {character: Characters.consonantSignBa, key: 'บ', rShiftCount: 1},
  {character: Characters.consonantSignSa, key: 'ส', rShiftCount: 2},
  {character: Characters.signSakot, key: '_', rShiftCount: 0},
  {character: Characters.vowelSignA, key: 'ะ', rShiftCount: 0},
  {character: Characters.vowelSignMaiSat, key: 'ั', rShiftCount: 0},
  {character: Characters.vowelSignAa, key: 'า', rShiftCount: 0},
  {character: Characters.vowelSignTallAa, key: 'ๅ', rShiftCount: 0},
  {character: Characters.vowelSignI, key: 'ิ', rShiftCount: 0},
  {character: Characters.vowelSignIi, key: 'ี', rShiftCount: 0},
  {character: Characters.vowelSignUe, key: 'ึ', rShiftCount: 0},
  {character: Characters.vowelSignUue, key: 'ื', rShiftCount: 0},
  {character: Characters.vowelSignU, key: 'ุ', rShiftCount: 0},
  {character: Characters.vowelSignUu, key: 'ู', rShiftCount: 0},
  {character: Characters.vowelSignO, key: 'ฎ', rShiftCount: 0},
  {character: Characters.vowelSignO, key: 'ั', rShiftCount: 1},
  {character: Characters.vowelSignOaBelow, key: 'ำ', rShiftCount: 0},
  {character: Characters.vowelSignOy, key: 'ย', rShiftCount: 2},
  {character: Characters.vowelSignE, key: 'เ', rShiftCount: 0},
  {character: Characters.vowelSignAe, key: 'แ', rShiftCount: 0},
  {character: Characters.vowelSignOo, key: 'โ', rShiftCount: 0},
  {character: Characters.vowelSignAi, key: 'ไ', rShiftCount: 0},
  {character: Characters.vowelSignThamAi, key: 'ใ', rShiftCount: 0},
  {character: Characters.vowelSignOaAbove, key: 'อ', rShiftCount: 3},
  {character: Characters.signMaiKang, key: 'ํ', rShiftCount: 0},
  {character: Characters.signTone1, key: '่', rShiftCount: 0},
  {character: Characters.signTone2, key: '้', rShiftCount: 0},
  {character: Characters.signKhuenTone3, key: '่', rShiftCount: 1},
  {character: Characters.signKhuenTone4, key: '้', rShiftCount: 1},
  {character: Characters.signKhuenTone5, key: '๊', rShiftCount: 1},
  {character: Characters.signRaHaam, key: '์', rShiftCount: 0},
  {character: Characters.signMaiSam, key: 'ๆ', rShiftCount: 0},
  {character: Characters.signKhuenLueKaran, key: '์', rShiftCount: 1},
  {character: Characters.combiningCryptogrammicDot, key: 'ฺ', rShiftCount: 1},
  {character: Characters.horaDigitZero, key: '๐', rShiftCount: 0},
  {character: Characters.horaDigitOne, key: '๑', rShiftCount: 0},
  {character: Characters.horaDigitTwo, key: '๒', rShiftCount: 0},
  {character: Characters.horaDigitThree, key: '๓', rShiftCount: 0},
  {character: Characters.horaDigitFour, key: '๔', rShiftCount: 0},
  {character: Characters.horaDigitFive, key: '๕', rShiftCount: 0},
  {character: Characters.horaDigitSix, key: '๖', rShiftCount: 0},
  {character: Characters.horaDigitSeven, key: '๗', rShiftCount: 0},
  {character: Characters.horaDigitEight, key: '๘', rShiftCount: 0},
  {character: Characters.horaDigitNine, key: '๙', rShiftCount: 0},
  {character: Characters.thamDigitZero, key: '๐', rShiftCount: 1},
  {character: Characters.thamDigitOne, key: '๑', rShiftCount: 1},
  {character: Characters.thamDigitTwo, key: '๒', rShiftCount: 1},
  {character: Characters.thamDigitThree, key: '๓', rShiftCount: 1},
  {character: Characters.thamDigitFour, key: '๔', rShiftCount: 1},
  {character: Characters.thamDigitFive, key: '๕', rShiftCount: 1},
  {character: Characters.thamDigitSix, key: '๖', rShiftCount: 1},
  {character: Characters.thamDigitSeven, key: '๗', rShiftCount: 1},
  {character: Characters.thamDigitEight, key: '๘', rShiftCount: 1},
  {character: Characters.thamDigitNine, key: '๙', rShiftCount: 1},
  {character: Characters.signWiang, key: 'ว', rShiftCount: 1},
  {character: Characters.signWiangwaak, key: 'ว', rShiftCount: 2},
  {character: Characters.signSawan, key: 'ส', rShiftCount: 3},
  {character: Characters.signKeow, key: 'ค', rShiftCount: 1},
  {character: Characters.signHoy, key: 'ห', rShiftCount: 1},
  {character: Characters.signDokmai, key: 'ด', rShiftCount: 1},
  {character: Characters.signReversedRotatedRana, key: 'ณ', rShiftCount: 1},
  {character: Characters.signMaiYamok, key: 'ๆ', rShiftCount: 1},
  {character: Characters.signKaan, key: 'ไ', rShiftCount: 1},
  {character: Characters.signKaankuu, key: 'ไ', rShiftCount: 2},
  {character: Characters.signSatkaan, key: 'ฯ', rShiftCount: 0},
  {character: Characters.signSatkaankuu, key: 'ฯ', rShiftCount: 1},
  {character: Characters.signHang, key: 'ห', rShiftCount: 2},
  {character: Characters.signCaang, key: 'ช', rShiftCount: 1}
];

export type KeyDict = {[key: string]: {[rShiftCount: number]: string}};

export function getKeyDict(): KeyDict {
  const results: KeyDict = {};
  for (const key of keys) {
    if (!results[key.key]) {
      results[key.key] = {};
    }
    results[key.key][key.rShiftCount] = key.character;
  }
  return results;
}
