name: Deploy on Github Pages
on:
  workflow_call:
jobs:
  deploy:
    name: Build and publish

    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: svelte-publish
